steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ["pull", "gcr.io/${PROJECT_ID}/tacview_base:latest"]
  id: pull base image

- name: 'gcr.io/cloud-builders/docker'
  args: ["build", '--cache-from',
            "gcr.io/${PROJECT_ID}/tacview_base:latest",
            "-t", "gcr.io/${PROJECT_ID}/tacview_client:${SHORT_SHA}",
            "."]
  id: build-tacview-image

- name: 'gcr.io/cloud-builders/docker'
  args: ["tag",
          "gcr.io/${PROJECT_ID}/tacview_client:${SHORT_SHA}",
          'gcr.io/${PROJECT_ID}/tacview_client:latest']
  id: tag-latest-image


- name: 'gcr.io/cloud-builders/docker'
  args: ["push",
          "gcr.io/${PROJECT_ID}/tacview_client:${SHORT_SHA}"]
  id: push-image

- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment
  - tacview
  - gaw=gcr.io/${PROJECT_ID}/tacview_client:${SHORT_SHA}
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=tacview-client-gaw-cluster'
  id: update-gaw-image

- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment
  - tacview
  - pgaw=gcr.io/${PROJECT_ID}/tacview_client:${SHORT_SHA}
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=tacview-client-gaw-cluster'
  id: update-pgaw-image

images: ["gcr.io/${PROJECT_ID}/tacview_client:latest",
         "gcr.io/${PROJECT_ID}/tacview_client:${SHORT_SHA}"]
