steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ["pull", "gcr.io/dcs-analytics-257714/tacview_base:latest"]
  id: pull base image

- name: 'gcr.io/cloud-builders/docker'
  args: ["build", '--cache-from',
            "gcr.io/dcs-analytics-257714/tacview_base:latest",
            "-t", "gcr.io/${PROJECT_ID}/tacview_client:${SHORT_SHA}",
            "."]
  id: build-tacview-image

- name: 'gcr.io/cloud-builders/docker'
  args: ["tag",
          "gcr.io/${PROJECT_ID}/tacview_client:${SHORT_SHA}",
          'gcr.io/${PROJECT_ID}/tacview_client:latest']
  id: tag-latest-image

images: ["gcr.io/${PROJECT_ID}/tacview_client:latest",
         "gcr.io/${PROJECT_ID}/tacview_client:${SHORT_SHA}"]


# - name: 'gcr.io/cloud-builders/gke-deploy'
#   args:
#   - run
#   - --image="gcr.io/${PROJECT_ID}/tacview_client:${SHORT_SHA}"
#   - --location="us-central-1"
#   - --cluster=[CLUSTER]
