apiVersion: apps/v1
kind: Deployment
metadata:
  name: tacview-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gaw
  template:
    metadata:
      labels:
        app: gaw
    spec:

      volumes:
      - name: google-cloud-key
        secret:
          secretName: pubsub-key
      containers:
      - name: tacview
        args: ["--host", "147.135.8.169", "--port", "42674", "--mode", "remote"]
        image: gcr.io/dcs-analytics-257714/tacview_client:be9ee6b
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
